### ISSUE TITLE
Cannot find the "One time transfer" task option on the user interface

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#105]
**Describe the bug**
I am not able to find the One time transfer task option when creating the task.

**To Reproduce**
1. Select S3 as the destination, and create a task.
2. When the task incur errors, clone and create another task

**Expected behavior**
Can select one time transfer task.

**Please complete the following information about the solution:**
- [x] Version: 2.3.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO8001) - Data Transfer Hub with aws-solutions-constructs: This template deploys an one-stop toolset for transferring data from different sources into AWS. Template version **v1.0.0**_".

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
<img width="643" alt="Screen Shot 2023-01-13 at 10 21 34" src="https://user-images.githubusercontent.com/2173635/212222244-37b4d992-7e48-4fe1-99ce-77aaef02da02.png">

**Additional context**

**Comment by JoeShi** [comment]
<img width="629" alt="Screen Shot 2023-01-13 at 10 23 54" src="https://user-images.githubusercontent.com/2173635/212222558-c052226c-96e1-4818-bbe3-eb2fd27fa2e7.png">

**Comment by YikaiHu** [comment]
Please turn off the **Enable S3 Event?**
Then, you can see the `One-Time Transfer` option
