### ISSUE TITLE
How to delete an error task

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#106]
**Describe the bug**
When a task incur error status, I cannot find a way to delete the related CloudFormation template.

**To Reproduce**
1. Create a task with error, for example, you can specify a AK/SK without enough permission.

**Expected behavior**
1. The CloudFormation being deleted.

**Please complete the following information about the solution:**
- [x] Version: v2.3.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO8001) - Data Transfer Hub with aws-solutions-constructs: This template deploys an one-stop toolset for transferring data from different sources into AWS. Template version **v1.0.0**_".

- [x] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository? yes.
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by YikaiHu** [comment]
Hi @JoeShi ,

Please choose the error task and click **Task Action**  and choose **Stop Task**.

![image](https://user-images.githubusercontent.com/34271744/212227673-e8c36331-8682-451f-bba1-d637e31829b8.png)

**Comment by JoeShi** [comment]
I have tried, but still failed to delete the stack.

**Comment by YikaiHu** [comment]
This is due to PVRE, public customer will not have this issue.
