### ISSUE TITLE
[BUG] S3 Event disables Eventbridge in the Source Bucket

### ISSUE THREAD

**Issue by B-Lukas** [awslabs/data-transfer-hub#110]
**Describe the bug**
When you create a S3 Data Transfer Hub Task and enable S3 Event (to trigger when an Object is created), `Send notifications to Amazon EventBridge for all events in this bucket` in the Source Bucket will always be disabled even if it was enabled before.

**To Reproduce**
1. Enable `Send notifications to Amazon EventBridge for all events in this bucket` in the Source Bucket
2. Create a new Task with `enable S3 Event` set to `Create`
3. The `Send notifications to Amazon EventBridge for all events in this bucket` will now be disabled

**Expected behavior**
Task creation with S3 Event set to Create should no disable Eventbridge for the Source Bucket

**Please complete the following information about the solution:**
- [ ] Version: v2.3.0
- [ ] Region: eu-central-1
- [ ] Was the solution modified from the version published on this repository? No

**Comment by YikaiHu** [comment]
Fixed in v2.4.0: https://github.com/awslabs/amazon-s3-data-replication-hub-plugin/commit/0baf83b9f0ec0ad2a26c79d3c83394a5e1b88d5d#diff-3b7e84ad2ef434d69b4e7ad2b8b92c98982203353944162ad58632fbb0775bd2
