### ISSUE TITLE
User interface does not allow destinationBucket in same account

### ISSUE THREAD

**Issue by kaplanan** [awslabs/data-transfer-hub#112]
**Describe the bug**
When using the [`DTHCLI`](https://github.com/aws-samples/data-transfer-hub-cli), one can configure for S3 Transfer Tasks, that the destinationBucket is in the same account. However, in the User Interface, there is no such option which results in issues when trying to transfer data between buckets that are located in the same account.

**Expected behavior**
The User Interface provides the same configuration parameters as the [`DTHCLI`](https://github.com/aws-samples/data-transfer-hub-cli) would via the [`config.yaml`](https://github.com/aws-samples/data-transfer-hub-cli/blob/main/config-example.yaml)

**Please complete the following information about the solution:**
- [x] Version: v2.4.0

- [x] Region: eu-central-1

**Comment by evalzy** [comment]
Hi Kaplanan

If you want to transfer the object within the same account, we recommend that you can use [S3 replication service](https://aws.amazon.com/getting-started/hands-on/replicate-data-using-amazon-s3-replication/). DTH is trying to solve the problem for transferring the object cross account, especially transfer object between GCR region and other partition.

**Comment by evalzy** [comment]
Hi Kaplanan

For those who want to use one account transfer the object between China region with other region, DTH provide the transfer as a  service supplement .
