### ISSUE TITLE
Enable Option to Explicitly Declare Using AES256 as Server Side Encryption 

### ISSUE THREAD

**Issue by shyl** [awslabs/data-transfer-hub#124]
**Is your feature request related to a problem? Please describe.**
It is a technical blocker of AWS opp 0064z00002D4kOaAAJ.

**Describe the feature you'd like**
The customer has enforced an SCP in its global region, so that every bucket under its AWS account will require an explicited declaration of SSE method of AES256 in its S3 API call, to be able to put any object into an S3 bucket.  However, DTH does not provide such an option and therefore will not add any option in calling S3:PutObject (or other relevant) API, therefore DTH write to my customer's bucket will fail.

**Additional context**

**Comment by YikaiHu** [comment]
Support in [v2.6.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.6.0)
