### ISSUE TITLE
Request add feature to support we have option to choose S3 bucket to hold prefix list file

### ISSUE THREAD

**Issue by yonghuizusa** [awslabs/data-transfer-hub#125]
**Is your feature request related to a problem? Please describe.**

We use DTH copy another team S3 bucket files, as of current DTH design, we have to put prefix list file into that team's S3 bucket, since we only get read only access, so we have to coordinate with another team to ask them place the prefix file, this is not always convenient

**Describe the feature you'd like**
Can we add a feature or option to allow us choose a the bucket we can put prefix list file in ? 

**Additional context**

**Comment by JoeShi** [comment]
duplicated with https://github.com/awslabs/data-transfer-hub/issues/97, will implement in v2.6

**Comment by YikaiHu** [comment]
Supported in [v2.6.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.6.0)
