### ISSUE TITLE
Add documentation of how to deploy the S3/ECR transfer task using CloudFormation

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#128]
**Is your feature request related to a problem? Please describe.**
Add documentation of how to deploy the S3/ECR transfer task using CloudFormation

**Describe the feature you'd like**
Deploy S3/ECR transfer task without UI.

**Additional context**

**Comment by YikaiHu** [comment]
Supported in [v2.6.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.6.0)
