### ISSUE TITLE
retry quota exceeded

### ISSUE THREAD

**Issue by lvtujingji** [awslabs/data-transfer-hub#129]
我在新加坡搭建了DTH
源端： 阿里SSO
目标： 新加坡 S3
遭遇了这个问题：
2023/11/23 04:31:26 S3> Unable to download edwdnh/promotion_alliance/product/logo/50cd9162332c42f0940f1629b7c33a28.jpeg with 14264 bytes start from 0 - operation error S3: GetObject, failed to get rate limit token, retry quota exceeded, 0 available, 10 requested
这是什么地方的限制，或者是写其他什么？

**Comment by lvtujingji** [comment]
另外我还注意到这种报错：
Unable to download edwdnh/promotionoduct/ogo/4b521254b190443da61fc40285faae9b.png with 3124 bvtes start from 0 -3.httpsoperation error S3: GetObiect, exceeded maximum number of attempts.error StatusCode: 0 RequestlD:, HostlD: , request send failed,Get"https://vunmai-static-files.oss-cn-beiing.aliyuncs.com/edwdnh/promotiol1254b190443da61fc40285faae9b.png?x-id=GetObiect":diatcp 8.131.208.202:443: i/o timeout

**Comment by YikaiHu** [comment]
Hi @lvtujingji , 请问上述两种错误，是偶发现象还是所有的文件都遇到了这种错误?

**Comment by YikaiHu** [comment]
看上去是网络流量被限流了，通常可以通过Terminate 现有的Worker 节点，让ASG 自动拉起新的节点来解决该问题。
