### ISSUE TITLE
KMS Key auto deleted after DTH ppl status to stopped

### ISSUE THREAD

**Issue by evalzy** [awslabs/data-transfer-hub#135]
**Is your feature request related to a problem? Please describe.**
KMS key still exist even DTH pipeline transfer task stopped

**Describe the feature you'd like**
Automatically delete KMS key when ppl transfer complete. 

**Additional context**

**Comment by YikaiHu** [comment]
Supported in [v2.6.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.6.0)
