### ISSUE TITLE
Src and Dest both support cross account replica

### ISSUE THREAD

**Issue by liangruibupt** [awslabs/data-transfer-hub#31]
Now, only Src or Dest support cross account replica
Src and Dest both support cross account replica

**Comment by JoeShi** [comment]
You can now transfer objects from/to another account. When you select **No** in "Is bucket in this account", then you have an option to select a credentials for the other account. 

![Screen Shot 2021-08-17 at 8 56 35 AM](https://user-images.githubusercontent.com/2173635/129647134-c40ee66f-e000-4636-9c12-26074a7a8592.png)

![Screen Shot 2021-08-17 at 8 56 50 AM](https://user-images.githubusercontent.com/2173635/129647151-f83dfcd7-d924-47ac-a77b-0629be765a2a.png)
