### ISSUE TITLE
Deployment guide in English

### ISSUE THREAD

**Issue by strowk** [awslabs/data-transfer-hub#34]
It looks like this page https://www.amazonaws.cn/en/solutions/data-replication-hub/ links Chineese deployment guide. I could not find it in English. Is it available? If not - please translate it

**Comment by JoeShi** [comment]
Sure. We will provide English deployment guide in next release.

**Comment by JoeShi** [comment]
English User Guide: https://github.com/awslabs/data-transfer-hub/blob/v2.0.0/docs/UserManual.md
English Deployment Guide: https://github.com/awslabs/data-transfer-hub#solution-deployment

**Comment by JoeShi** [comment]
Please create another issue, if you need further assistance.
