### ISSUE TITLE
Task failed if the source bucket enabled SSE-KMS

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#45]
If the source bucket has enable SSE-KMS, the task will fail. The instance profile associated with the EC2 does not have the permission to use KMS.

**Comment by YikaiHu** [comment]
Currently you can refer to this guide:

https://github.com/awslabs/data-transfer-hub/blob/v2.0.0/docs/S3-SSE-KMS-Policy.md
