### ISSUE TITLE
Support for data transfer from commercial regions to GovCloud regions

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#46]

**Comment by fergfamster** [comment]
it already works with GovCloud, have you tried it? They will update the docs to show support but its already working today.

**Comment by JoeShi** [comment]
We have add support for GovCloud, and updated the doc. Thank you.

**Comment by bpbraun** [comment]
How do you set up the IAM role appropriately for this if my source bucket is in commercial and my destination bucket is in govcloud?

I've been trying to get this two work but I'm getting 403 error when I check the logs.  I'm running datatransferhub in my commercial region (Virginia) and trying to transfer to govcloud where I'm using the key associated with an IAM with admin privileges stored as a secret in my commercial account.
