### ISSUE TITLE
Support transfer data from public dataset in S3

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#53]
## User Scenario
There are a few open source dataset on https://registry.opendata.aws/. Customers want to transfer those data into their own AWS account for further study. 

Or transfer those public dataset from standard regions to China regions/GovCloud.

**Comment by YikaiHu** [comment]
Already implemented in [v2.4.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.4.0).
