### ISSUE TITLE
Add an parameter to eliminate the object list comparison

### ISSUE THREAD

**Issue by JoeShi** [awslabs/data-transfer-hub#56]
By default, the finder process will list all objects in both source and destination and find the delta collection. Add a parameter to eliminate the list action in destination bucket. It can save up some time on finder process. 

The typical user scenario is migration or one-time transfer.

**Comment by YikaiHu** [comment]
Thanks Joe.

This feature has been released in v2.1 .

Customers can set the parameter **Need Data Comparison before Transfer** to  **No** to eliminate the comparison.
