### ISSUE TITLE
No visable log message on the portal

### ISSUE THREAD

**Issue by teaguexiao** [awslabs/data-transfer-hub#6]
I accidentally input a space character in the parameter store and after I start the task it hang on the starting/In Progress stage. I cannot get direct logging/error message on the portal. I have to find the corresponding log group in CloudWatch to find what goes wrong.

If there's a tab on the portal to display critical error or a link to related CloudWatch log would be more user friendly!

**Comment by JoeShi** [comment]
Thanks. Will look into it.

**Comment by Ganvor1124** [comment]
同感

**Comment by YikaiHu** [comment]
Already implemented in [v2.4.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.4.0).
