### ISSUE TITLE
S3 replication task setup doesn't list all secrets stored in Secrets Manager

### ISSUE THREAD

**Issue by tomclukies** [awslabs/data-transfer-hub#61]
See attached screenshot. When selecting a secret for the Credentials Store Option, data-transfer-hub only fetches 10 Secrets Manager results. It looks like it selects the first 10 with AWS's default sorting. This renders the rest of my secrets un-selectable. There is no way to filter this list to get the secrets I'd like to either. 

DTH should be able to list all secrets in AWS Secrets Manger and/or filter with user input. 

Thank you!

![Screen Shot 2021-09-13 at 5 06 20 PM](https://user-images.githubusercontent.com/45573063/133168397-0a5906dc-0379-4a34-b28c-fea44352b2fa.png)

**Comment by ParanoidKevin** [comment]
Any update on this?

**Comment by YikaiHu** [comment]
Hi @tomclukies and @ParanoidKevin , 
This bug has been resolved in the latest version.
Please refer to https://www.amazonaws.cn/en/solutions/data-transfer-hub/
Thanks!
