### ISSUE TITLE
aws overseas cannot synchronize domestic

### ISSUE THREAD

**Issue by Joker-Cch** [awslabs/data-transfer-hub#71]
Cloudformation is deployed in the ap-southeast-1 region, and the cn-northwest-1 key is configured in the secret manager, but after ap-southeast-1 s3 put object, it cannot be put to cn-northwest-1, prompting "Got an error uploading file-operation error S3: PutObject, https response error StatusCode: 400, api error InvalidToken: The provided token is malformed or otherwise invalid."

**Comment by YikaiHu** [comment]
Hi, please check the formate of the credentials in AWS Secrets Manager in ap-southeast-1 region. 
It should follow:
```
{
  "access_key_id": "<Your Access Key ID>",
  "secret_access_key": "<Your Access Key Secret>"
}
```
And this credential has the correct permission, you can refer to this Guide: https://github.com/awslabs/data-transfer-hub/blob/v2.0.0/docs/IAM-Policy.md
