### ISSUE TITLE
Data transfer hub solution to work with Azure Blob storage

### ISSUE THREAD

**Issue by jamalarif** [awslabs/data-transfer-hub#72]
Customer requesting to migrate data from Azure Blob storage to S3 using automated methods. Data transfer hub works with other cloud storage providers but doesn't currently support Azure Blob storage.

**Comment by YikaiHu** [comment]
Sorry for the late reply, this feature already supported by [AWS DataSync](https://docs.aws.amazon.com/datasync/latest/userguide/creating-azure-blob-location.html).
