### ISSUE TITLE
Issue with S3 Job UI: Secrets field only pulls first page from Secrets Manager

### ISSUE THREAD

**Issue by gderoule** [awslabs/data-transfer-hub#78]
**Describe the bug**
As title indicates, when setting up an S3 replication job, the Secret field for both source and destination has broken pagination where it only displays the first page from Secrets Manager. 

**To Reproduce**
1. Launch stack with the Cloudformation template on this main GitHub page
2. Login to DTH UI
3. Navigate to the S3 job UI
4. Under "Source" or "Destination there is a field to select the Secret to use with the job, which shows Secrets within Secrets Manager as a drop down.
5. Only the first page of Secrets shows up within the drop down. 

**Expected behavior**
The expectation here is that all Secrets Manager keys should be aggregated to the drop down for selection.

**Please complete the following information about the solution:**
- [ v1.0.0] Version
- [us-west-2 ] Region
- [Yes and No ] Was the solution modified from the version published on this repository? --- We noticed the behavior on our own modified template (just has some dynamic VPC/Subnet selection). We then launched the template directly from this GIT and it showed the same behavior.
- [No] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [No] I didn't see any errors pointing to this problem. It returns Secrets, just not all of them.

**Screenshots**
Hard to screenshot this. Isn't any errors, just a behavior.

**Additional context**
I re-ordered the Secrets so that the secret that we want to use with DTH is available on the first page, and then it showed up within S3 Job UI within DTH.

Tried new spinup after creating the Secret, no go.

Tried it in multiple browesers (Firefox, Opera, Safari) same issue.

Tried clearing cache (full purge, + machine restart) no go.

**Comment by YikaiHu** [comment]
@gderoule Hi, please update the Data Transfer Hub stack by this link: https://www.amazonaws.cn/en/solutions/data-transfer-hub/

After you updated the stack, please don't forget to create invalidation for the Data Transfer Hub Distribution in the CloudFront.
