### ISSUE TITLE
Found retire version of python3.6 runtime created when creating the solution stack.

### ISSUE THREAD

**Issue by yexingok** [awslabs/data-transfer-hub#84]
**Describe the bug**

Hi, we receive an email from AWS about retire of python3.6 runtime lambda,
After check-in with following commands:

```
aws lambda list-functions --function-version ALL --region cn-north-1 --output text --query "Functions[?Runtime=='python3.6'].FunctionArn” 
```

We notice there is a lambda function name as “projectname-CustomerCDKBucketDeploymentXXX” is a python3.6 lambda function belongs to the data-transfer-hub

**To Reproduce**

1. Go to the link: https://awslabs.github.io/data-transfer-hub/zh/deployment 
2. Follow option2,  Deploy the solution in AWS China region cn-north-1  (template version: (SO8001) - Data Transfer Hub with aws-solutions-constructs: This template deploys an one-stop toolset for transferring data from different sources into AWS. Template version v2.1.1) 
3. run command: 
aws lambda list-functions --function-version ALL --region cn-north-1 --output text --query "Functions[?Runtime=='python3.6'].FunctionArn” 

You will find the python3.6 function named as "projectname-CustomerCDKBucketDeploymentXXX" can be found as part of the new launched stack.

Note:
I launched the solution on 2022-04-25, can still see this defect, template version: v2.1.1

**Expected behavior**

Update this lambda function runtime to  python3.8 or python3.9 will be good.
If this function is a requirement to build the stack, then it will be a major issue after  July 18th, 
According to AWS's email, they will refuse to create python3.6 runtime after that time.

**Please complete the following information about the solution:**
- [x] Version: [v2.1.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO8001) - Data Transfer Hub with aws-solutions-constructs: This template deploys an one-stop toolset for transferring data from different sources into AWS. Template version **v1.0.0**_".

- [x] Region: [e.g. cn-north-1]
- [ ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes - not quote issue.
- [x] Were there any errors in the CloudWatch Logs? No error.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

* outputs of python3.6 lambda function:
<img width="802" alt="python36-lambda1" src="https://user-images.githubusercontent.com/368081/169230387-787e3d3f-9e67-4528-9860-d5909ef73d51.png">
* the function belongs to the cloudformation stack:
<img width="803" alt="python36-lambda2" src="https://user-images.githubusercontent.com/368081/169230423-627a2e6e-8519-4d02-86cf-c3d3ef90f4a5.png">

**Additional context**
Below is the AWS email for our reference:

邮件标题：
[需要采取行动] Amazon Lambda服务终止对 Python 3.6 的支持
邮件内容：
您好，
我们联系您是因为我们发现您的亚马逊云科技服务账户当前有一个或多个使用 Python 3.6 运行时的 Lambda 函数。
我们将终止 Amazon Lambda 中对 Python 3.6 的支持。这是在 2021 年 12 月 23 日达到 Python 3.6 生命周期终止 (EOL) [1] 之后的结果。
如 Lambda 运行时支持策略 [2] 中所述，Lambda 中对语言运行时的支持结束分两个阶段进行。从 2022 年 7 月 18 日开始，Lambda 将不再对 Lambda 函数使用的 Python 3.6 运行时应用安全补丁和其他更新，并且使用 Python 3.6 的函数将不再有资格获得技术支持。
此外，您将无法再使用 Python 3.6 运行时创建新的 Lambda 函数。从 2022 年 8 月 17 日开始，您将无法再使用 Python 3.6 运行时更新现有函数。
我们建议您在 2022 年 8 月 17 日之前将现有的 Python 3.6 函数升级到 Python 3.9。
技术支持结束不影响您函数功能执行。您的函数将继续运行。但是，他们将运行在一个不再由我们维护或修补的不受支持的运行时。
以下命令显示了如何使用 Amazon CLI [3] 列出使用 Python 3.6 的特定区域中的所有函数。要在您的账户中查找所有此类功能，请重复此命令：
北京区域：aws lambda list-functions --function-version ALL --region cn-north-1 --output text --query "Functions[?Runtime=='python3.6'].FunctionArn"
如果您有任何问题或者疑虑，请联系亚马逊云科技中国支持团队[4]。

**Comment by JoeShi** [comment]
thanks for reporting. we are working on it.

**Comment by yexingok** [comment]
Thanks for quick response 👍

**Comment by yexingok** [comment]
Hi team, do we have any updates or need more info?

**Comment by yexingok** [comment]
@YikaiHu thank you 👍

**Comment by YikaiHu** [comment]
Hi @yexingok, this issue has been solve in our latest version, https://www.amazonaws.cn/en/solutions/data-transfer-hub/
Please upgrade the CloudFormation Stack with the follow guide:

1.	Go to CloudFormation, choose the Data Transfer Hub console main stack.
2.	Click Update
3.	Click Replace current template
4.	Enter template link:
  a.	Global: https://aws-gcr-solutions.s3.amazonaws.com/data-transfer-hub/latest/DataTransferHub-cognito.template
  b.	China: https://aws-gcr-solutions.s3.cn-north-1.amazonaws.com.cn/data-transfer-hub/latest/DataTransferHub-openid.template
5.	Click Next, keep the Parameters unchanged
6.	Click Next
7.	Click Next
8.	Choose I acknowledge that AWS CloudFormation might create IAM resources.
9.	Click Update Stack 
10.	Re-create a S3 Transfer Task

**Comment by yexingok** [comment]
@YikaiHu  thank you very much 👍 !
We will arrange update in next week.

**Comment by yexingok** [comment]
Hi  @YikaiHu 

I succ using the above v2.2 template update the stack,

However after updating, it is not possible to create a new S3 transfer job, the job just shows like this:

![can-not-create-job-succ](https://user-images.githubusercontent.com/368081/183030909-f01ac528-b3c1-43ba-9bc9-304b1f66e854.jpg)

And there is no cloudfomation s3 job are created.

I can see there are error message in the APICfnWorkflow like this:

![datahub-error-20220805](https://user-images.githubusercontent.com/368081/183030737-6e3077f5-5af3-4bb7-b001-996cf4a48b8a.jpg)

I also tried with v2.2 template to create a new stack from beginning, it have the same issue, 
have you test the template? thanks.

Please help, thanks.

**Comment by YikaiHu** [comment]
Hi @yexingok , you need to create an invalidation in CloudFront, then, refresh the page before you creating a new S3 task.

**Comment by yexingok** [comment]
Hi @YikaiHu 

Thank you for quick response!  I do the following step as you mentioned and it works for me now:

1. create an invalidation in cloudfront for /* (so there is no CDN cache).
2. open an in-private window with Edge browser. (so there is no browser cache).
3. re-create the s3 job.

FYI - maybe it is worth to mention somewhere in the step or README :)

**Comment by YikaiHu** [comment]
We will add this upgrade guide in our documentation.

1.	Go to CloudFormation, choose the Data Transfer Hub console main stack.
2.	Click Update
3.	Click Replace current template
4.	Enter template link:
a.	Global: https://aws-gcr-solutions.s3.amazonaws.com/data-transfer-hub/latest/DataTransferHub-cognito.template
b.	China: https://aws-gcr-solutions.s3.cn-north-1.amazonaws.com.cn/data-transfer-hub/latest/DataTransferHub-openid.template

5.	Click Next, keep the Parameters unchanged
6.	Click Next
7.	Click Next
8.	Choose I acknowledge that AWS CloudFormation might create IAM resources.
9.	Click Update Stack 
10.   Create an invalidation in CloudFront for /* .
11.	Re-create a S3 Transfer Task
