### ISSUE TITLE
[Issue] Create new S3 transfer task failed, caused by is not authorized to perform: logs:DescribeMetricFilters 

### ISSUE THREAD

**Issue by YikaiHu** [awslabs/data-transfer-hub#89]
**Describe the bug**
Create new S3 transfer task failed, caused by is not authorized to perform: logs:DescribeMetricFilters on resource: arn:aws:logs:xxxxxx.

**Please complete the following information about the solution:**
- [ ] Version: v1.0.0
- [ ] Version: v2.0.x
- [ ] Version: v2.1.1
- [ ] Version: v2.1.2

**Screenshots**
<img width="1060" alt="Xnip2022-07-08_10-56-47" src="https://user-images.githubusercontent.com/34271744/177908109-3c412bab-e6f6-4a40-9887-0f1b5ab144a2.png">

**Comment by YikaiHu** [comment]
This is because of a recent change on AWS service policy, please follow below actions to fix:

1. Go to AWS [IAM role console](https://us-east-1.console.aws.amazon.com/iamv2/home#/roles), and search for APICfnWorkflowCreateTaskCfnFnServi, and choose the role which name is DataTransferHub-APICfnWorkflowCreateTaskCfnFnServixxx-xxxxxxxxxxx.
2. Click Add Permissions, and choose Attach Policies.
3. Search for CloudWatchLogsFullAccess, and click Attach Policies.
4. Create a new S3 transfer task.

**Comment by YikaiHu** [comment]
Fixed

**Comment by victorconan** [comment]
> This issue has been solve in our latest version, https://www.amazonaws.cn/en/solutions/data-transfer-hub/ Please upgrade the CloudFormation Stack with the follow guide:
> 
> 1. Go to CloudFormation, choose the Data Transfer Hub console main stack.
> 2. Click Update
> 3. Click Replace current template
> 4. Enter template link:
>    a.	Global: https://aws-gcr-solutions.s3.amazonaws.com/data-transfer-hub/latest/DataTransferHub-cognito.template
>    b.	China: https://aws-gcr-solutions.s3.cn-north-1.amazonaws.com.cn/data-transfer-hub/latest/DataTransferHub-openid.template
> 5. Click Next, keep the Parameters unchanged
> 6. Click Next
> 7. Click Next
> 8. Choose I acknowledge that AWS CloudFormation might create IAM resources.
> 9. Click Update Stack
> 10. Re-create a S3 Transfer Task

This template update caused error:
```
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.
```

**Comment by YikaiHu** [comment]
> > This issue has been solve in our latest version, https://www.amazonaws.cn/en/solutions/data-transfer-hub/ Please upgrade the CloudFormation Stack with the follow guide:
> > 
> > 1. Go to CloudFormation, choose the Data Transfer Hub console main stack.
> > 2. Click Update
> > 3. Click Replace current template
> > 4. Enter template link:
> >    a.	Global: https://aws-gcr-solutions.s3.amazonaws.com/data-transfer-hub/latest/DataTransferHub-cognito.template
> >    b.	China: https://aws-gcr-solutions.s3.cn-north-1.amazonaws.com.cn/data-transfer-hub/latest/DataTransferHub-openid.template
> > 5. Click Next, keep the Parameters unchanged
> > 6. Click Next
> > 7. Click Next
> > 8. Choose I acknowledge that AWS CloudFormation might create IAM resources.
> > 9. Click Update Stack
> > 10. Re-create a S3 Transfer Task
> 
> This template update caused error:
> 
> ```
> Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.
> ```

Hi, let's track in https://github.com/awslabs/data-transfer-hub/issues/98
