### ISSUE TITLE
python3.6 is no longer supported

### ISSUE THREAD

**Issue by bkc1** [awslabs/data-transfer-hub#94]
**Describe the bug**
Cloudformation deployment fails due to deprecated v3.6 runtime on 'CustomCDKBucketDeployment' resource. Received the following error...

Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: a031c6e0-099f-400c-b178-46d8fd90eed4)" (RequestToken: 7c6f9c88-0ae4-0f27-8d61-0a780cc6e230, HandlerErrorCode: InvalidRequest)

**To Reproduce**
Launch the stack.

**Expected behavior**
CFN template expected to deploy without error.

**Please complete the following information about the solution:**
- [ ] Version: v1.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO8001) - Data Transfer Hub with aws-solutions-constructs: This template deploys an one-stop toolset for transferring data from different sources into AWS. Template version **v1.0.0**_".

- [ ] Region: [e.g. us-east-1] us-east-1
- [ ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? n/a
- [ ] Were there any errors in the CloudWatch Logs? n/a

**Comment by YikaiHu** [comment]
Hi, @bkc1 this is an issue, we are working on fix it the issue on the WW Solutions Library, there are some process to fix the issue. 

Currently, please refer to the link on the [China Solutions Library](https://www.amazonaws.cn/en/solutions/data-transfer-hub/).

**Comment by YikaiHu** [comment]
Fixed.
