### ISSUE TITLE
feature request - whitelist the prefix in target bucket

### ISSUE THREAD

**Issue by cryptopalxyz** [awslabs/data-transfer-hub#97]
**Is your feature request related to a problem? Please describe.**
Currently it only supports to put a file to "whitelist" the prefix in the source S3 buckets.
In our use case, the source S3 is not managed by us and we have read only role.
In this case, we would not be able to "put" this file.

**Describe the feature you'd like**
It would be good if we can put the "whitelist" file in target bucket.

**Additional context**
NA

@YikaiHu @qiaoshi

**Comment by YikaiHu** [comment]
Supported in [v2.6.0](https://github.com/awslabs/data-transfer-hub/releases/tag/v2.6.0)
