### ISSUE TITLE
Unable to run S3 transfer task successfully

### ISSUE THREAD

**Issue by victorconan** [awslabs/data-transfer-hub#98]
Hi, I used to use data transfer hub to transfer S3 data from us-east-2 to cn-northwest-1. But recently I was not able to run the task successfully. I cannot see any error message regarding why the task failed. Do you have any suggestion on how to diagnose it?

Thanks

**Comment by YikaiHu** [comment]
Hi @victorconan, what's the version of Data Transfer Hub and your failed DTH S3 plugin? 

You can check the **earliest** error message in CloudFormation console **Event** page.

**Comment by victorconan** [comment]
> Hi @victorconan, what's the version of Data Transfer Hub and your failed DTH S3 plugin?
> 
> You can check the **earliest** error message in CloudFormation console **Event** page.
This is the version of DTH:
```
(SO8001) - Data Transfer Hub with aws-solutions-constructs: This template deploys an one-stop toolset for transferring data from different sources into AWS. Template version v2.0.4
```
Thanks!

**Comment by YikaiHu** [comment]
@victorconan , v2.0.4 uses the python 3.6 so it can not be deployed anymore.

And I noticed that you are having problems during upgrading: https://github.com/awslabs/data-transfer-hub/issues/89.

There are two workaround:
1. Delete the old Data Transfer Hub and deploy the latest version.
2. Manually update the python version of your current Data Transfer Hub(v2.0.4), then upgrade to the latest version of Data Transfer Hub

    - Go to the AWS CloudFormation Console
    - Click your Data Transfer Hub main stack
    - Click **Template** tab
    - Click **View in Designer** button
    - Search for `python3.6` in the template box at the bottom of the screen, and replace it with python3.9
    - <img width="1641" alt="image" src="https://user-images.githubusercontent.com/34271744/194734529-06b27e9d-3ab6-463a-86ab-2549dea043ec.png">
    - Click "Create Stack" icon in the upper left of the screen
    - <img width="327" alt="image" src="https://user-images.githubusercontent.com/34271744/194734588-8fc68f08-0ac8-4994-b449-73f893fe2cc8.png">
    - Click **Next**, **Next**, **Create**
    - Then follow the [guide](https://github.com/awslabs/data-transfer-hub/issues/89#issuecomment-1200643365) to upgrade to the latest version.

**Comment by victorconan** [comment]
> @victorconan , v2.0.4 uses the python 3.6 so it can not be deployed anymore.
> 
> And I noticed that you are having problems during upgrading: #89.
> 
> There are two workaround:
> 
> 1. Delete the old Data Transfer Hub and deploy the latest version.
> 2. Manually update the python version of your current Data Transfer Hub(v2.0.4), then upgrade to the latest version of Data Transfer Hub
>    
>    * Go to the AWS CloudFormation Console
>    * Click your Data Transfer Hub main stack
>    * Click **Template** tab
>    * Click **View in Designer** button
>    * Search for `python3.6` in the template box at the bottom of the screen, and replace it with python3.9
>    * <img alt="image" width="1641" src="https://user-images.githubusercontent.com/34271744/194734529-06b27e9d-3ab6-463a-86ab-2549dea043ec.png">
>    * Click "Create Stack" icon in the upper left of the screen
>    * <img alt="image" width="327" src="https://user-images.githubusercontent.com/34271744/194734588-8fc68f08-0ac8-4994-b449-73f893fe2cc8.png">
>    * Click **Next**, **Next**, **Create**
>    * Then follow the [guide](https://github.com/awslabs/data-transfer-hub/issues/89#issuecomment-1200643365) to upgrade to the latest version.

Thanks! It works now!
